appName: "AzteRadio"

botToken: "MTE3MjI4NjQwMjUyNDg5MzE5NA.GoBu7X.bzJPUDVMP52GhRIsbuiPuO5pqGIJnesbHVtIT8"

clientId: "1172286402524893194"

geniusApiKey: ""

embedColour: "#2B2D31"

enableAnalytics: false

enableAutocomplete: true

player:
    leaveOnEndDelay: 300000 # 5 minutes
    leaveOnStopDelay: 300000 # 5 minutes
    leaveOnEmptyDelay: 1.728e+8 # 48 hours
    deafenBot: true

emojis:
    stop: "â¹"
    skip: "â­"
    queue: "ğŸ“œ"
    pause: "â¯"
    lyrics: "ğŸ“œ"
    back: "â®"

proxy:
    enable: false
    connectionUrl: "http://111.111.111.111:8080"

cookies:
    useCustomCookie: false
    youtubeCookie: ""
